## Plotly Data Visulization (Part I )

In [40]:
# import Plotly library
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [41]:
name = ['Jawad', 'Ali', 'Ahmed', 'Hassan', 'Hussain']
height = [5.5, 6.0, 5.8, 5.9, 6.1]

#import plotly
import plotly.express as px

# Create a plotly figure
fig = px.bar(x=name, y=height, title='Height of Individuals')

# SHow the figure
fig.show()

#SAVE Plotly figure as in png format
fig.write_image("./Outputs/height_plot.png")

# save as standlone HTML file
fig.write_html("./Outputs/height_plot.html")

# Plots on Titanic Data Set

In [42]:
#import dataset
df = sns.load_dataset('titanic')

# Check the Data frame 
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [43]:
# Scatter plot using Plotly

df.dropna(inplace=True)
fig = px.scatter(df, x='age', y='fare', color='sex', size= 'age', title= 'plot of Titanic passengers age vs fare')
fig.show()

fig.write_image("./Outputs/titanic_scatter.png", scale=3) # how to save the plot in high resolution

In [44]:
# Go Scatter plot using Plotly

import plotly.graph_objects as go

# create a simple line chart

fig = go.Figure(data=go.Scatter(x=[1, 2, 3, 4], y=[10, 11, 12, 13]))
fig.show()

In [45]:
# Customizing the line chart with markers and line style

fig.update_layout(
    title='Customized Line Chart',
    xaxis_title=dict(text='Number'),
    yaxis_title=dict(text='Value'),
    showlegend=True
)

In [49]:
# heatmap using plotly




data = np.random.rand(10, 10)

heatmap = go.Heatmap (z = data)

fig = go.Figure(data = [heatmap])

fig.show()

In [50]:
# heat map corr of titanic Dataframe

fig = px.imshow(df[['age', 'fare']].corr())
fig.show()

In [57]:
iris =sns.load_dataset ('iris')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [61]:
fig = px.imshow(iris[["sepal_length", "sepal_width", "petal_length", "petal_width"]].corr())
fig.show()

In [ ]:
fig = px.imshow(df[['age', 'fare']].corr())
fig.show()